services:
  db:
    image: postgres:17
    container_name: vacado_db
    environment:
      POSTGRES_DB: vacado_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vacado_db
      DB_USER: postgres
      DB_PASSWORD: postgres
volumes:
  pgdata:


